export const PROFESSIONAL_AFFIRMATIONS = [
  { en: "I chose this work because I believe in the power of human connection.", es: "Elegí este trabajo porque creo en el poder de la conexión humana." },
  { en: "My presence can be meaningful, even when I cannot change the circumstances.", es: "Mi presencia puede ser significativa, incluso cuando no puedo cambiar las circunstancias." },
  { en: "I do not need to have every answer to make a difference.", es: "No necesito tener todas las respuestas para marcar una diferencia." },
  { en: "I create space for people to feel seen, heard, and respected.", es: "Creo un espacio para que las personas se sientan vistas, escuchadas y respetadas." },
  { en: "I honor the courage it takes for someone to trust me with their story.", es: "Honro el valor que requiere confiarme la historia personal de alguien." },
  { en: "I can help someone recognize possibilities they may not yet see for themselves.", es: "Puedo ayudar a alguien a reconocer posibilidades que quizá todavía no ve por sí mismo." },
  { en: "My work contributes to healing one conversation, one person, and one community at a time.", es: "Mi trabajo contribuye a la sanación, una conversación, una persona y una comunidad a la vez." },
  { en: "I trust that meaningful change often begins quietly.", es: "Confío en que los cambios significativos suelen comenzar silenciosamente." },
  { en: "I am here to support people as they discover their own strength, meaning, and direction.", es: "Estoy aquí para apoyar a las personas mientras descubren su propia fortaleza, significado y dirección." },
  { en: "The work I do matters, even when its impact is not immediately visible.", es: "El trabajo que realizo importa, incluso cuando su impacto no es visible de inmediato." },
  { en: "I showed up with what I had today, and that has value.", es: "Hoy me presenté con lo que tenía, y eso tiene valor." },
  { en: "I can acknowledge what was difficult without questioning my entire purpose.", es: "Puedo reconocer lo que fue difícil sin cuestionar todo mi propósito." },
  { en: "Not every session needs a breakthrough to be meaningful.", es: "No todas las sesiones necesitan un gran avance para ser significativas." },
  { en: "I cannot remove every burden, but I can help someone feel less alone while carrying it.", es: "No puedo eliminar todas las cargas, pero puedo ayudar a alguien a sentirse menos solo mientras las lleva." },
  { en: "I am allowed to feel affected by this work and still remain grounded in my role.", es: "Puedo sentirme afectado por este trabajo y, aun así, mantenerme firme en mi rol." },
  { en: "One difficult day does not define the professional I am.", es: "Un día difícil no define al profesional que soy." },
  { en: "I can return to my purpose without demanding perfection from myself.", es: "Puedo volver a mi propósito sin exigirme perfección." },
  { en: "I will continue learning, adapting, and becoming.", es: "Continuaré aprendiendo, adaptándome y transformándome." },
  { en: "I remember why I began.", es: "Recuerdo por qué comencé." },
  { en: "I am here to serve with knowledge, compassion, integrity, and humanity—and that is meaningful work.", es: "Estoy aquí para servir con conocimiento, compasión, integridad y humanidad; y ese es un trabajo significativo." },
] as const;
