/** Latin American Spanish translations for public Kimorah pages that predate i18next keys. */
export const KIMORAH_ES: Record<string, string> = {
  "Welcome": "Bienvenido",
  "This is your space.": "Este es tu espacio.",
  "Choose what you want to nurture today.": "Elige lo que deseas cultivar hoy.",
  "Every choice is a step toward your well-being.": "Cada elección es un paso hacia tu bienestar.",
  "Kindness": "Bondad", "Immersive": "Inmersivo", "Mission": "Misión", "MISSION": "MISIÓN",
  "Oneness": "Unidad", "Revitalization": "Revitalización", "Acceptance": "Aceptación", "Harmony": "Armonía",
  "Back": "Volver", "Back to Home": "Volver al inicio", "Coming soon.": "Próximamente.",
  "Learn More": "Conoce más", "Explore": "Explorar", "Journal": "Diario", "View Groups": "Ver grupos",
  "Renew your energy. Reclaim your truth.": "Renueva tu energía. Recupera tu verdad.",
  "Rise into your fullest self.": "Álzate hacia tu ser más pleno.",
  "The 12 Laws of Inner Truths": "Las 12 leyes de las verdades internas", "Reflective Cycle": "Ciclo reflexivo",
  "Breath:": "Respiración:", "What new beginning flows with my breath?": "¿Qué nuevo comienzo fluye con mi respiración?",
  "What can I embrace as it is?": "¿Qué puedo aceptar tal como es?", "What principles guide me right now?": "¿Qué principios me guían en este momento?",
  "What story or insight can I share?": "¿Qué historia o reflexión puedo compartir?", "How can I bring clarity to my emotions?": "¿Cómo puedo dar claridad a mis emociones?",
  "What truth needs to be spoken/expressed?": "¿Qué verdad necesita ser dicha o expresada?", "Where can I find equilibrium today?": "¿Dónde puedo encontrar equilibrio hoy?",
  "How can I grow through my limits?": "¿Cómo puedo crecer a través de mis límites?", "What keeps me grounded in truth?": "¿Qué me mantiene con los pies en la verdad?",
  "Which path will I consciously choose?": "¿Qué camino elegiré conscientemente?", "What cycle is ready to be completed?": "¿Qué ciclo está listo para completarse?",
  "How can I recognize what I’ve learned?": "¿Cómo puedo reconocer lo que he aprendido?", "Write. Reflect. Realign.": "Escribe. Reflexiona. Realinéate.",
  "Healthy Juices or Snacks": "Jugos o meriendas saludables", "That Boost the": "Que fortalecen el", "Immune System": "sistema inmunitario",
  "Detox": "Desintoxicación", "Release what": "Suelta lo que", "no longer serves": "ya no te sirve",
  "Energy Vent": "Liberación de energía", "Clear stress.": "Libera el estrés.", "Breathe deeper.": "Respira más profundo.",
  "Let Go Interventions": "Intervenciones para soltar", "Release. Reset.": "Suelta. Reinicia.", "Move forward.": "Sigue adelante.",
  "Somatic Methods": "Métodos somáticos", "Reconnect.": "Reconecta.", "Recover. Restore.": "Recupérate. Restaura.",
  "Sleep Hygiene": "Higiene del sueño", "Rest deeply.": "Descansa profundamente.", "Rise renewed.": "Despierta renovado.",
  "Daily Reflections": "Reflexiones diarias", "Every step you take today builds a stronger tomorrow.": "Cada paso que das hoy construye un mañana más fuerte.",
  "You don’t have to go through": "No tienes que pasar por esto", "this alone. We are here for you.": "a solas. Estamos aquí para ti.",
  "Bereavement": "Duelo", "Counseling": "Consejería", "Compassionate, personalized": "Apoyo compasivo y personalizado",
  "support for your": "para acompañarte en tu", "grief journey.": "proceso de duelo.", "Planning for": "Planificación para el", "End of Life": "final de la vida",
  "Make empowered decisions": "Toma decisiones con confianza", "and create a plan that": "y crea un plan que", "honors your wishes.": "honre tus deseos.",
  "Death Doula": "Doula de duelo", "Services": "Servicios", "Gentle guidance and": "Orientación y presencia amable",
  "presence for you and": "para ti y", "your loved ones.": "tus seres queridos.", "Legal Advice for": "Asesoría legal para el",
  "Understand your rights and": "Comprende tus derechos y", "options with end-of-life": "opciones legales para el", "legal guidance.": "final de la vida.",
  "Help with Belongings": "Ayuda con pertenencias", "Compassionate assistance": "Ayuda compasiva", "in sorting and organizing": "para clasificar y organizar",
  "a recently deceased": "las pertenencias de una", "person’s possessions.": "persona recién fallecida.", "Bereavement Support Group": "Grupo de apoyo para el duelo",
  "Connect with others who understand.": "Conecta con otras personas que comprenden.", "Share, heal, and grow together in a safe space.": "Compartan, sanen y crezcan juntos en un espacio seguro.",
  "In acceptance, we create space for healing.": "En la aceptación, creamos espacio para sanar.", "You are not alone. We walk with you.": "No estás solo. Caminamos contigo.",
  "Small acts. Big impact.": "Pequeños actos. Gran impacto.", "Kindness begins with you.": "La bondad comienza contigo.",
  "Acts of Kindness": "Actos de bondad", "Self-Care & Self-Love": "Autocuidado y amor propio", "Support & Give Back": "Apoya y retribuye", "Kindness Meditations": "Meditaciones de bondad",
  "Kind Words": "Palabras amables", "Lend a Hand": "Tiende una mano", "Small Gestures": "Pequeños gestos", "Small Donations": "Pequeñas donaciones", "Be Present": "Hazte presente",
  "Pause & Breathe": "Pausa y respira", "Nourish Your Body": "Nutre tu cuerpo", "Speak Kindly": "Háblate con amor", "Honor Your Heart": "Honra tu corazón",
  "Healthy Recipes": "Recetas saludables", "Environmental": "Medioambientales", "Foundations": "Fundaciones", "Children & Education": "Niñez y educación",
  "Health & Wellness": "Salud y bienestar", "Animal Welfare": "Bienestar animal", "Loving-Kindness": "Amor bondadoso", "Meditation": "Meditación",
  "Gratitude": "Gratitud", "Compassion": "Compasión", "Share a compliment": "Comparte un cumplido", "or a note of": "o una nota de", "appreciation.": "agradecimiento.",
  "Offer help to": "Ofrece ayuda a", "someone who": "alguien que", "needs it.": "la necesite.", "Hold the door,": "Sostén la puerta,", "share a smile,": "comparte una sonrisa,", "brighten a day.": "alegra un día.",
  "Save the world": "Salva el mundo", "one donation": "una donación", "at a time.": "a la vez.",
  "Listen deeply.": "Escucha profundamente.", "Your presence": "Tu presencia", "is powerful.": "es poderosa.", "Take a moment": "Tómate un momento", "to center": "para centrarte", "and reset.": "y renovarte.",
  "Eat well, hydrate,": "Come bien, hidrátate,", "rest, and move": "descansa y muévete", "with love.": "con amor.", "Be gentle with": "Sé amable contigo.", "yourself. You are": "Tal como eres,", "enough.": "eres suficiente.",
  "Journal, reflect,": "Escribe, reflexiona", "and celebrate": "y celebra", "your growth.": "tu crecimiento.",
  "Find balance within. Calm your body,": "Encuentra el equilibrio interior. Calma tu cuerpo,", "quiet your mind, and come home to yourself.": "aquieta tu mente y vuelve a ti.",
  "Vagus Nerve": "Nervio vago", "Coping Skills": "Estrategias de afrontamiento", "Progressive": "Relajación muscular", "Muscle Relaxation": "progresiva",
  "Guided Meditation": "Meditación guiada", "for Grounding": "para conectar con la tierra", "Grounding": "Conexión con la tierra", "Techniques": "Técnicas",
  "Lyrical Dance /": "Danza lírica /", "Somatics": "Somática", "Breathing": "Respiración", "Gratitude Journal": "Diario de gratitud",
  "EFT (Emotional": "EFT (Técnica de", "Freedom Technique)": "Liberación Emocional)", "Tap, release, and reset.": "Golpea suavemente, libera y reinicia.",
  "Ease stress, overwhelm,": "Alivia el estrés, el agobio", "and emotional blocks.": "y los bloqueos emocionales.", "In harmony, we heal. In balance, we thrive.": "En armonía, sanamos. En equilibrio, prosperamos.",
  "We rise together. We give back.": "Crecemos juntos. Retribuimos.", "Earth & Climate": "Tierra y clima", "Children Education": "Educación infantil", "Arts & Culture": "Arte y cultura", "Research & Science": "Investigación y ciencia",
  "Want to get involved?": "¿Quieres participar?", "Your support fuels change.": "Tu apoyo impulsa el cambio.", "Make an Impact": "Genera un impacto",
  "Deep healing. Whole you.": "Sanación profunda. Tu ser completo.", "Grief Counseling": "Consejería de duelo", "Somatic Practices": "Prácticas somáticas", "Hypnotherapy": "Hipnoterapia", "Ancestral Healing": "Sanación ancestral", "Medicine Music": "Música medicinal", "Guided Meditations": "Meditaciones guiadas",
  "Workshops": "Talleres", "Podcast": "Pódcast", "You don't have to do this alone.": "No tienes que hacerlo a solas.", "We're here to walk this path with you.": "Estamos aquí para recorrer este camino contigo.",
  "Align. Connect. Become.": "Alinéate. Conecta. Conviértete.", "Spirituality": "Espiritualidad", "Holistic Coaching": "Acompañamiento holístico", "Life Coach": "Coach de vida", "Mediumship": "Mediumnidad", "Telepathy": "Telepatía", "Sacred Rituals": "Rituales sagrados", "Conscious Living": "Vida consciente",
  "Morning Presence Meditation": "Meditación matutina de presencia", "Reiki Energy Healing Session": "Sesión de sanación energética Reiki", "New": "Nuevo", "Live": "En vivo", "Play": "Reproducir", "Book Now": "Reservar", "All Levels": "Todos los niveles",
  // Kindness page card copy
  "Support causes": "Apoya causas", "that protect": "que protegen", "our planet.": "nuestro planeta.",
  "Help create brighter": "Ayuda a crear un futuro", "futures through": "más prometedor mediante la", "education.": "educación.",
  "Support physical": "Apoya iniciativas de", "and mental health": "salud física y mental", "initiatives.": "para la comunidad.",
  "Advocate and": "Defiende y apoya", "support our": "el bienestar de", "animal friends.": "nuestros amigos animales.",
  "Cultivate compassion": "Cultiva la compasión", "for yourself and others.": "por ti y por los demás.",
  "Focus on the good": "Concéntrate en la bondad", "and light within.": "y la luz que hay en ti.",
  "Open your heart.": "Abre tu corazón.", "Send kindness out": "Comparte bondad", "into the world.": "con el mundo.", "NEW": "NUEVO",
  // Harmony page card copy
  "Activate your body’s natural": "Activa la respuesta natural", "calming response and": "de calma de tu cuerpo y", "support nervous system": "favorece la regulación del", "regulation.": "sistema nervioso.",
  "Release tension from": "Libera la tensión desde", "head to toe and invite": "la cabeza hasta los pies e invita", "deep relaxation.": "a una relajación profunda.",
  "Soothing meditations to": "Meditaciones relajantes para", "help you feel present,": "sentirte presente,", "centered, and safe.": "en equilibrio y a salvo.",
  "Simple practices to help": "Prácticas sencillas para", "you feel connected,": "sentirte en conexión,", "steady, and supported.": "estable y acompañado.",
  "Move, express, and release": "Muévete, exprésate y libera", "through the wisdom of": "a través de la sabiduría de", "your body.": "tu cuerpo.",
  "Breath practices to calm": "Prácticas de respiración para calmar", "your mind, regulate your": "tu mente, regular tus", "emotions, and restore ease.": "emociones y recuperar la tranquilidad.",
  "Cultivate appreciation, shift": "Cultiva el agradecimiento, transforma", "your mindset, and invite": "tu perspectiva e invita", "more joy into your life.": "más alegría a tu vida.",
  // Immersive page
  "Compassionate support to navigate loss, honor your emotions, and find meaning.": "Apoyo compasivo para transitar la pérdida, honrar tus emociones y encontrar sentido.",
  "Heal & Remember": "Sana y recuerda", "Reconnect with your body, release stored tension, and restore balance.": "Reconecta con tu cuerpo, libera la tensión acumulada y recupera el equilibrio.",
  "Return to Self": "Vuelve a ti", "Access your subconscious mind to heal, reframe patterns, and create lasting change.": "Accede a tu mente subconsciente para sanar, replantear patrones y crear cambios duraderos.",
  "Transform Within": "Transfórmate desde dentro", "Reconnect with your lineage and receive guidance and healing across generations.": "Reconecta con tu linaje y recibe guía y sanación a través de las generaciones.",
  "Honoring Roots": "Honra tus raíces", "Therapeutic sound journeys and medicine music to uplift, soothe, and transform.": "Viajes sonoros terapéuticos y música medicinal para elevarte, calmarte y transformarte.",
  "Listen. Heal. Rise.": "Escucha. Sana. Renace.", "Find inner peace, clarity, and resilience through mindful guided practices.": "Encuentra paz interior, claridad y resiliencia mediante prácticas guiadas de atención plena.",
  "Center & Restore": "Céntrate y restáurate", "Step away. Reconnect. Return renewed.": "Haz una pausa. Reconecta. Regresa renovado.", "Wellness Retreats": "Retiros de bienestar", "Ancestral Journeys": "Viajes ancestrales", "Healing Retreats": "Retiros de sanación", "Inner Peace Escapes": "Escapadas de paz interior",
  "Rest, recharge, and nurture your mind, body, and spirit in nature.": "Descansa, recarga energías y nutre tu mente, cuerpo y espíritu en la naturaleza.", "Sacred experiences to connect with your roots and ancestral wisdom.": "Experiencias sagradas para conectar con tus raíces y tu sabiduría ancestral.", "Deep healing experiences to release, transform, and realign your life.": "Experiencias de sanación profunda para liberar, transformar y realinear tu vida.", "Immerse in stillness, reflection, and practices that bring you back to yourself.": "Sumérgete en la quietud, la reflexión y prácticas que te devuelven a ti.",
  "Listen. Reflect. Grow.": "Escucha. Reflexiona. Crece.", "Episode One": "Episodio uno", "Episode Two": "Episodio dos", "Episode Three": "Episodio tres", "Episode Four": "Episodio cuatro",
  // Oneness page
  "PATHWAYS TO ONENESS": "CAMINOS HACIA LA UNIDAD", "SPECIALIZED EXPERIENCES": "EXPERIENCIAS ESPECIALIZADAS", "Faith & Religious Affiliation": "Fe y afiliación religiosa", "Intermediate": "Intermedio",
  "Calm your mind, open your heart, and reconnect within.": "Calma tu mente, abre tu corazón y reconecta con tu interior.", "Explore spiritual teachings, practices, and sacred wisdom.": "Explora enseñanzas espirituales, prácticas y sabiduría sagrada.", "Mind, body, and spirit support for inner balance and healing.": "Apoyo para mente, cuerpo y espíritu que fomenta el equilibrio interior y la sanación.", "Clarity, purpose, and aligned action for the life you desire.": "Claridad, propósito y acciones coherentes con la vida que deseas.", "Live and upcoming workshops to expand your consciousness.": "Talleres en vivo y próximos para expandir tu conciencia.",
  "Develop connection with spirit, receive guidance, and strengthen intuition.": "Desarrolla tu conexión con el espíritu, recibe guía y fortalece tu intuición.", "Explore the power of mind-to-mind communication and energetic connection.": "Explora el poder de la comunicación entre mentes y la conexión energética.", "Honor your path and explore diverse traditions with open heart.": "Honra tu camino y explora distintas tradiciones con el corazón abierto.", "Participate in transformative ceremonies and ancestral practices.": "Participa en ceremonias transformadoras y prácticas ancestrales.", "Integrate spiritual wisdom into everyday life.": "Integra la sabiduría espiritual en la vida cotidiana.",
  // Mission page
  "EXPLORE CAUSES": "EXPLORA CAUSAS", "PRIORITY PROGRAMS": "PROGRAMAS PRIORITARIOS", "PRIORITY RESEARCH": "INVESTIGACIÓN PRIORITARIA", "FEATURED PARTNERS": "ORGANIZACIONES DESTACADAS", "View All ›": "Ver todo ›", "Protect our home": "Protege nuestro hogar", "Invest in their future": "Invierte en su futuro", "Inspire. Create. Transform.": "Inspira. Crea. Transforma.", "Discover. Understand. Advance.": "Descubre. Comprende. Avanza.",
  "When the Earth Changes,": "Cuando la Tierra Cambia,", "We Change Too": "Nosotros También",
  "A psychoeducational curriculum offering support and processing for people indirectly affected by the earthquake in Venezuela.": "Currículo psicoeducativo de apoyo y procesamiento para personas afectadas indirectamente por el terremoto de Venezuela.",
  "DESIGNED FOR MENTAL HEALTH PROFESSIONALS": "DISEÑADO PARA PROFESIONALES DE LA SALUD MENTAL",
  "Evidence-based. Trauma-informed. Integrative and culturally sensitive approaches.": "Basado en evidencia. Informado por trauma. Enfoques integrativos y culturalmente sensibles.",
  "EXPLORE SESSIONS": "EXPLORAR SESIONES", "WATCH INTRODUCTORY VIDEO": "VER VIDEO INTRODUCTORIO",
  // Coquí research components
  "COQUÍ RESEARCH DATA": "DATOS DE LA INVESTIGACIÓN DEL COQUÍ", "Overview": "Resumen", "Key Findings": "Hallazgos principales", "Demographics": "Datos demográficos", "Emotional Responses": "Respuestas emocionales", "Somatic Responses": "Respuestas somáticas", "Time & Exposure": "Tiempo y exposición", "Location & Displacement": "Ubicación y desplazamiento", "Methodology": "Metodología", "Survey": "Encuesta", "About the Study": "Acerca del estudio",
  "AT A GLANCE": "DATOS GENERALES", "IMPRINTING SCORE DISTRIBUTION": "DISTRIBUCIÓN DEL ÍNDICE DE HUELLA EMOCIONAL", "Average Score": "Puntuación promedio", "TIME SINCE LAST EXPOSURE": "TIEMPO DESDE LA ÚLTIMA EXPOSICIÓN", "EMOTIONAL RESPONSES": "RESPUESTAS EMOCIONALES", "SOMATIC RESPONSES": "RESPUESTAS SOMÁTICAS", "TIME OF EXPOSURE": "MOMENTO DE EXPOSICIÓN", "Top Mentions": "Menciones principales", "Most Impactful": "Mayor impacto", "QUALITATIVE INSIGHTS": "HALLAZGOS CUALITATIVOS", "EMOTIONAL THEMES": "TEMAS EMOCIONALES", "SOMATIC THEMES": "TEMAS SOMÁTICOS", "Word Cloud": "Nube de palabras", "WHAT THE COQUÍ CALL MEANS TO PARTICIPANTS": "LO QUE EL CANTO DEL COQUÍ SIGNIFICA PARA LAS PERSONAS PARTICIPANTES", "ORIGINAL LOCATION": "LUGAR DE ORIGEN", "CURRENT LOCATION": "UBICACIÓN ACTUAL", "ABOUT THIS DATA": "ACERCA DE ESTOS DATOS",
  // Words of Kindness page
  "WORDS OF KINDNESS": "PALABRAS DE BONDAD", "Be gentle with yourself. Be kind to others. Shine love.": "Sé amable contigo. Sé amable con los demás. Irradia amor.",
  "You are not alone": "No estás a solas", "Take your time": "Tómate tu tiempo", "I believe in you": "Creo en ti", "You are doing great": "Lo estás haciendo muy bien", "Choose peace": "Elige la paz",
  "It’s okay to take a break": "Está bien tomarte un descanso", "You have value": "Eres una persona valiosa", "Keep going": "Sigue adelante", "Thank you for being you": "Gracias por ser tú", "Your feelings are valid": "Tus sentimientos son válidos", "One step at a time": "Un paso a la vez",
  "I’m proud of you": "Siento orgullo por ti", "You make a difference": "Tú haces la diferencia", "You are worthy": "Eres digno de amor", "You bring light": "Tú traes luz", "You are stronger than you think": "Eres más fuerte de lo que crees", "Be kind to yourself": "Trátate con bondad",
  "You are capable": "Eres capaz", "Progress, not perfection": "Progreso, no perfección", "You are enough": "Eres suficiente", "Trust the process": "Confía en el proceso", "I love you": "Te quiero", "One day at a time": "Un día a la vez", "Stay present": "Vive el presente", "You Are Enough": "Eres suficiente", "You": "Tú", "Matter": "Importas",
  // Lend a Hand page
  "WAYS YOU CAN": "MANERAS DE", "LEND A HAND": "DAR UNA MANO", "Small acts. Big impact. Together, we can make a difference.": "Pequeños actos. Gran impacto. Juntos podemos marcar la diferencia.",
  "VISIT AND BRIGHTEN A DAY": "VISITA Y ALEGRA EL DÍA", "Spend time at an assisted living community and read a book, poem, or magazine to someone.": "Comparte tiempo en una residencia de vida asistida y léele a alguien un libro, un poema o una revista.",
  "SHARE YOUR SKILLS": "COMPARTE TUS HABILIDADES", "Offer your talents to a school or organization—tutoring, mentoring, technology, photography, design, music, and more.": "Ofrece tus talentos a una escuela u organización: tutoría, mentoría, tecnología, fotografía, diseño, música y mucho más.",
  "VOLUNTEER AT A HOSPICE": "HAZ VOLUNTARIADO EN CUIDADOS PALIATIVOS", "Provide comfort, companionship, and support to patients and families during a tender time.": "Brinda consuelo, compañía y apoyo a pacientes y familias durante un momento delicado.",
  "VOLUNTEER AT A SHELTER": "HAZ VOLUNTARIADO EN UN REFUGIO", "Help provide a safe, welcoming space and support those rebuilding their lives.": "Ayuda a brindar un espacio seguro y acogedor, y apoya a quienes reconstruyen sus vidas.",
  "HELP AT A SOUP KITCHEN": "AYUDA EN UN COMEDOR COMUNITARIO", "Serve meals, prepare food, or simply share kindness with those in need.": "Sirve comidas, prepara alimentos o simplemente comparte bondad con quienes lo necesitan.",
  "BRING ART AND JOY TO HEALING": "LLEVA ARTE Y ALEGRÍA A LA SANACIÓN", "Offer your creativity—art, music, or crafts—to children in hospitals and brighten their day.": "Comparte tu creatividad —arte, música o manualidades— con niños hospitalizados y alegra su día.",
  "BUY SOMEONE’S GROCERIES": "COMPRA LOS ALIMENTOS DE ALGUIEN", "Lighten someone’s load with a simple act of generosity.": "Alivia la carga de alguien con un sencillo acto de generosidad.",
  "GIVE A HUG": "DA UN ABRAZO", "Sometimes, a hug is exactly what someone needs.": "A veces, un abrazo es exactamente lo que alguien necesita.",
  "ASK AND LISTEN": "PREGUNTA Y ESCUCHA", "Ask someone, “Do you need a hand?” You never know how much it might mean.": "Pregúntale a alguien: «¿Necesitas una mano?». Nunca sabes cuánto puede significar.",
  "KINDNESS IS CONTAGIOUS.": "LA BONDAD ES CONTAGIOSA.", "BE THE REASON.": "SÉ EL MOTIVO.",
};
