import mongoose from "mongoose";
import { Curriculums } from "../models/curriculum-model";
import { Sessions } from "../models/session-model";

type Pair = [string, string];
const l = ([en, es]: Pair) => ({ en, es });
const items = (pairs: Pair[]) => pairs.map((pair, order) => ({ order, title: l(pair), prompts: [] }));
const group = (order: number, pairs: Pair[], heading?: Pair, intro?: Pair) => ({
  order,
  heading: l(heading ?? ["", ""]),
  intro: l(intro ?? ["", ""]),
  items: items(pairs),
});
const section = (groups: ReturnType<typeof group>[], intro?: Pair) => ({
  intro: l(intro ?? ["", ""]),
  groups,
});
const simple = (pairs: Pair[], intro?: Pair) => section([group(0, pairs)], intro);

const presentation = {
  body: l(["Each participant will have the opportunity to introduce themselves, sharing only what feels comfortable. This is a space where vulnerability is welcome and sharing is an invitation, not an obligation.", "Cada participante tendrá la oportunidad de presentarse, compartiendo únicamente aquello con lo que se sienta cómodo. Este es un espacio donde la vulnerabilidad es bienvenida y compartir es una invitación, no una obligación."]),
  prompts: [
    l(["How would you like us to address you during the group?", "¿Cómo te gustaría que nos dirigiéramos a ti durante el grupo?"]),
    l(["Is there anything you want the group to know to better support you? (Optional)", "¿Hay algo que quieras que el grupo sepa para apoyarte mejor? (Opcional)"]),
  ],
  reminder: l(["Everyone has the right to say “Pass” if they prefer not to answer a question.", "Todas las personas tienen derecho a decir “Paso” si prefieren no responder una pregunta."]),
};

const buildSession5 = () => ({
  order: 4, number: 5,
  title: l(["Control, acceptance, and the present moment", "Control, aceptación y el momento presente"]),
  mainTopic: [l(["Anxiety", "Ansiedad"]), l(["Presence", "Presencia"]), l(["Psychological flexibility", "Flexibilidad psicológica"])],
  presentation,
  sections: {
    concepts: simple(items5Concepts),
    objectives: simple(items5Objectives),
    psychoeducation: section([
      group(0, items5Explain, ["Explain", "Explicar"]),
      group(1, items5Anxiety, ["Understanding anxiety", "Comprender la ansiedad"]),
      group(2, items5Act, ["Acceptance and Commitment Therapy (ACT)", "Terapia de Aceptación y Compromiso (ACT)"], ["Explain:", "Explicar:"]),
      group(3, items5Polyvagal, ["Polyvagal Theory", "Teoría Polivagal (Polyvagal Theory)"], ["When our nervous system perceives a threat, it may respond automatically through different survival strategies:", "Cuando nuestro sistema nervioso percibe una amenaza, puede responder automáticamente mediante diferentes estrategias de supervivencia:"]),
      group(4, items5Highlight, ["Emphasize that", "Resaltar que"]),
    ], ["This session integrates Acceptance and Commitment Therapy (ACT) and Polyvagal Theory to understand how our body and mind respond after a traumatic experience.", "Esta sesión integra conceptos de la Terapia de Aceptación y Compromiso (Acceptance and Commitment Therapy - ACT) y la Teoría Polivagal (Polyvagal Theory) para comprender cómo responde nuestro cuerpo y nuestra mente después de una experiencia traumática."]),
    intervention: simple(items5Intervention, ["Focused on:", "Enfocada en:"]),
    processing: simple(items5Processing, ["Suggested questions:", "Preguntas sugeridas:"]),
  },
  closing: l(["Anxiety is not the enemy; it is a signal that our body is trying to protect us. We can learn from the past and plan for the future, but neither can be lived today. The present is the only place where we can act, make decisions, and live according to our values. Each time we consciously return to the here and now, we strengthen our ability to respond to uncertainty with greater calm, clarity, and flexibility. It is not about controlling everything that happens, but choosing how we want to respond in this moment.", "La ansiedad no es el enemigo; es una señal de que nuestro cuerpo está intentando protegernos. Podemos aprender del pasado y planificar el futuro, pero ninguno de ellos puede vivirse hoy. El presente es el único lugar donde podemos actuar, tomar decisiones y vivir de acuerdo con nuestros valores. Cada vez que regresamos conscientemente al aquí y al ahora fortalecemos nuestra capacidad para responder con mayor calma, claridad y flexibilidad frente a la incertidumbre. No se trata de controlar todo lo que sucede, sino de elegir cómo queremos responder en este momento."]),
  feedback: [l(["Share a practice that helps you return to the present moment.", "Comparte una práctica que te ayude a regresar al momento presente."]), l(["What learning or reflection are you taking from the session? (Optional)", "¿Qué aprendizaje o reflexión te llevas de la sesión? (Opcional)"])],
  therapeuticApproach: l(["Acceptance and Commitment Therapy (ACT), Polyvagal Theory, and Mindfulness.", "Terapia de Aceptación y Compromiso (ACT), Teoría Polivagal (Polyvagal Theory) y Mindfulness."]),
  clinicalReference: l(["This session integrates principles of ACT, Polyvagal Theory, and mindfulness practices to understand anxiety as an adaptive nervous-system response, promote acceptance of what cannot be controlled, and strengthen the ability to return to the present through emotional-regulation and grounding strategies.", "Esta sesión integra principios de la Terapia de Aceptación y Compromiso (ACT), la Teoría Polivagal y prácticas de mindfulness para comprender la ansiedad como una respuesta adaptativa del sistema nervioso, promover la aceptación de aquello que no puede controlarse y fortalecer la capacidad de regresar al momento presente mediante estrategias de regulación emocional y grounding."]),
});

const buildSession6 = () => ({
  order: 5, number: 6,
  title: l(["Rebuilding myself: Self-care, self-esteem, and inner strength", "Reconstruyéndome: Autocuidado, autoestima y fortaleza interior"]),
  mainTopic: [l(["Self-care", "Autocuidado"]), l(["Self-esteem", "Autoestima"]), l(["Self-concept", "Autoconcepto"]), l(["Recovering motivation", "Recuperando la motivación"])],
  presentation,
  sections: {
    concepts: simple(items6Concepts),
    objectives: simple(items6Objectives),
    psychoeducation: section([
      group(0, items6Explain, ["Explain", "Explicar"]),
      group(1, items6PhysicalCare, ["The importance of physical self-care", "Importancia del autocuidado físico"], ["Explain how the body and mind work together. Highlight the importance of:", "Explicar cómo el cuerpo y la mente trabajan juntos. Destacar la importancia de:"]),
      group(2, items6Cbt, ["Cognitive Behavioral Therapy (CBT)", "Terapia Cognitivo-Conductual (CBT)"], ["CBT proposes that thoughts, emotions, behaviors, and what we believe about ourselves continually influence one another.", "CBT propone que existe una relación constante entre pensamientos, emociones, comportamientos y lo que creemos de nosotros mismos."]),
      group(3, items6Adaptive, ["Adaptive coping strategies", "Estrategias adaptativas"]),
      group(4, items6Maladaptive, ["Maladaptive coping strategies", "Estrategias desadaptativas"]),
    ], ["This session integrates Cognitive Behavioral Therapy (CBT) concepts to understand how our thoughts, emotions, and behaviors influence one another.", "Esta sesión integra conceptos de la Terapia Cognitivo-Conductual (Cognitive Behavioral Therapy - CBT) para comprender cómo nuestros pensamientos, emociones y comportamientos se influyen mutuamente."]),
    intervention: simple(items6Intervention, ["Focused on:", "Enfocada en:"]),
    processing: simple(items6Processing, ["Suggested questions:", "Preguntas sugeridas:"]),
  },
  closing: l(["Recovery depends not only on what happens to us, but also on the relationship we build with ourselves. The way we speak to ourselves can become a source of criticism or strength. Every small act of self-care, every more compassionate thought, and every step forward strengthens our ability to keep rebuilding our life. It is not about returning to who we were before the earthquake; it is about recognizing that we survived, that we continue learning, and that each day offers an opportunity to become the person we want to be.", "La recuperación no depende únicamente de lo que nos ocurre, sino también de la relación que construimos con nosotros mismos. La manera en que nos hablamos puede convertirse en una fuente de crítica o en una fuente de fortaleza. Cada pequeño acto de autocuidado, cada pensamiento más compasivo y cada paso que damos hacia adelante fortalecen nuestra capacidad para seguir reconstruyendo nuestra vida. No se trata de volver a ser quienes éramos antes del terremoto; se trata de reconocer que hemos sobrevivido, que seguimos aprendiendo y que cada día tenemos la oportunidad de convertirnos en la persona que queremos ser."]),
  feedback: [l(["Complete one phrase: “I can…”, “I will…”, or “I am becoming…”", "Completa una de las siguientes frases: “Yo puedo…”, “Yo voy a…”, o “Me estoy convirtiendo en…”"]), l(["What learning or reflection are you taking from the session? (Optional)", "¿Qué aprendizaje o reflexión te llevas de la sesión? (Opcional)"])],
  therapeuticApproach: l(["Cognitive Behavioral Therapy (CBT), Behavioral Activation, and Positive Psychology.", "Terapia Cognitivo-Conductual (CBT), Activación Conductual (Behavioral Activation) y Psicología Positiva."]),
  clinicalReference: l(["This session incorporates CBT principles to understand the relationship among thoughts, emotions, and behaviors; Behavioral Activation to promote the gradual return of meaningful activities; and Positive Psychology to strengthen self-concept, self-esteem, resilience, and personal strengths through healthier inner dialogue and self-care strategies.", "Esta sesión incorpora principios de la Terapia Cognitivo-Conductual (CBT) para comprender la relación entre pensamientos, emociones y comportamientos, la Activación Conductual para promover el restablecimiento gradual de actividades significativas y la Psicología Positiva para fortalecer el autoconcepto, la autoestima, la resiliencia y las fortalezas personales mediante un diálogo interno más saludable y estrategias de autocuidado."]),
});

const buildSession7 = () => ({
  order: 6, number: 7,
  title: l(["Purpose and rebuilding meaning", "Propósito y reconstrucción del significado"]),
  mainTopic: [l(["Meaning", "Sentido"]), l(["Purpose", "Propósito"]), l(["Community", "Comunidad"])],
  presentation,
  sections: {
    concepts: simple(items7Concepts),
    objectives: simple(items7Objectives),
    psychoeducation: section([group(0, items7Psychoeducation, ["Explain", "Explicar"])], ["This session integrates principles of Logotherapy, Positive Psychology, and the therapeutic value of healing in community.", "Esta sesión integra principios de la Logoterapia, la Psicología Positiva y el valor terapéutico de la sanación en comunidad."]),
    intervention: section([
      group(0, items7Intervention, ["Focused on", "Enfocada en"]),
      group(1, items7Invitation, ["Each participant will be invited, if they wish, to share", "Cada participante será invitado, si así lo desea, a compartir"]),
    ]),
    processing: simple(items7Processing, ["Suggested questions:", "Preguntas sugeridas:"]),
  },
  closing: l(["We do not choose tragedy, but we can choose how to respond to it. Our purpose does not erase pain, but it can help us live with greater intention, connection, and compassion. Throughout these weeks, each person arrived seeking support and also became a source of support for someone else. Healing does not happen only within us; it can grow stronger when a community sees, hears, and accompanies us. Every shared story, respected silence, and word of support has contributed to this group’s collective process.", "No elegimos la tragedia, pero sí podemos elegir cómo responder a ella. Nuestro propósito no borra el dolor, pero puede ayudarnos a vivir con mayor intención, conexión y compasión. A lo largo de estas semanas, cada persona llegó buscando apoyo para sí misma. Sin embargo, también se convirtió, de manera consciente o inconsciente, en una fuente de apoyo para alguien más. La sanación no solo ocurre dentro de nosotros; también puede fortalecerse cuando nos sentimos vistos, escuchados y acompañados por una comunidad. Cada historia compartida, cada silencio respetado y cada palabra de apoyo han contribuido al proceso colectivo de este grupo."]),
  feedback: items7Feedback.map(l),
  therapeuticApproach: l(["Logotherapy, Positive Psychology, and Yalom’s Therapeutic Factors for Group Psychotherapy.", "Logoterapia, Psicología Positiva y Factores Terapéuticos de Yalom para la Psicoterapia de Grupo."]),
  clinicalReference: l(["This session integrates Logotherapy to facilitate the rebuilding of purpose and meaning after adversity, Positive Psychology to recognize strengths and post-traumatic growth, and Yalom’s Therapeutic Factors to promote group cohesion, interpersonal learning, altruism, and community healing through mutual recognition and closure.", "Esta sesión integra principios de la Logoterapia para facilitar la reconstrucción del propósito y el significado después de la adversidad, la Psicología Positiva para reconocer fortalezas y crecimiento postraumático, y los Factores Terapéuticos de Yalom para promover la cohesión grupal, el aprendizaje interpersonal, el altruismo y la sanación en comunidad mediante el reconocimiento mutuo y el cierre del proceso grupal."]),
});

const items5Concepts: Pair[] = [["Anxiety is a normal response that can help or hinder us depending on its intensity and duration.", "La ansiedad es una respuesta normal que puede ayudarnos o dificultarnos, dependiendo de su intensidad y duración."], ["We can learn from the past and plan for the future, but we can act only in the present.", "Podemos aprender del pasado y planificar el futuro, pero solo podemos actuar en el presente."], ["ACT promotes accepting what we cannot control and committing to actions aligned with our values.", "La Terapia de Aceptación y Compromiso (ACT) promueve la aceptación de aquello que no podemos controlar y el compromiso con acciones alineadas a nuestros valores."], ["Polyvagal Theory explains how our nervous system responds automatically to threat.", "La Teoría Polivagal explica cómo nuestro sistema nervioso responde automáticamente ante situaciones de amenaza."], ["Living one hour, one day, or one week at a time can reduce emotional overload.", "Vivir una hora, un día o una semana a la vez puede disminuir la sobrecarga emocional."], ["Being present supports emotional regulation and psychological flexibility.", "Estar presente favorece la regulación emocional y la flexibilidad psicológica."]];
const items5Objectives: Pair[] = [["Understand how anxiety develops after a traumatic experience.", "Comprender cómo se desarrolla la ansiedad después de una experiencia traumática."], ["Differentiate planning for the future from trying to control it.", "Diferenciar entre planificar el futuro y tratar de controlarlo."], ["Learn strategies for returning to the present moment.", "Aprender estrategias para regresar al momento presente."], ["Recognize automatic nervous-system responses to stress.", "Reconocer las respuestas automáticas del sistema nervioso frente al estrés."], ["Strengthen the ability to respond more flexibly to uncertainty.", "Fortalecer la capacidad de responder con mayor flexibilidad ante la incertidumbre."]];
const items5Explain: Pair[] = [["After trauma, the mind commonly travels constantly between the past and future.", "Después de una experiencia traumática es común que nuestra mente viaje constantemente entre el pasado y el futuro."], ["The past may bring memories, guilt, sadness, or situations we wish we could change.", "El pasado puede traer recuerdos, culpa, tristeza o situaciones que desearíamos cambiar."], ["The future may create uncertainty, worry, and fear about what could happen.", "El futuro puede generar incertidumbre, preocupación y miedo por lo que podría suceder."], ["Although we can learn from the past and plan the future, neither is happening now.", "Aunque podemos aprender del pasado y planificar el futuro, ninguno de los dos está ocurriendo en este momento."], ["The present is the only place where we can act, make decisions, and care for ourselves.", "El único lugar donde podemos actuar, tomar decisiones y cuidar de nosotros mismos es el presente."], ["Living one hour, day, or week at a time can reduce overwhelm.", "Vivir una hora, un día o una semana a la vez puede disminuir la sensación de sentirse abrumado."], ["Planning is healthy; trying to control the future often increases anxiety.", "Planificar el futuro es saludable; intentar controlarlo suele aumentar la ansiedad."]];
const items5Anxiety: Pair[] = [["Anxiety is a normal emotion that prepares us for challenges, changes, or possible danger.", "La ansiedad es una emoción normal cuya función es prepararnos para responder ante retos, cambios o posibles peligros."], ["Moderate anxiety can help us stay alert, motivated, organized, and ready to act, solve problems, protect ourselves, and adapt.", "Un nivel moderado de ansiedad puede ayudarnos a mantenernos atentos, motivados, organizados y preparados para actuar. Puede impulsarnos a resolver problemas, protegernos y adaptarnos a nuevas situaciones."], ["Intense, persistent, or hard-to-regulate anxiety can interfere with clear thinking, decisions, and enjoyment of the present.", "Cuando la ansiedad es intensa, persistente o difícil de regular, puede interferir con nuestra capacidad para pensar con claridad, tomar decisiones y disfrutar del momento presente."], ["The goal is not to eliminate anxiety, but to recognize when it is useful and when it needs regulation.", "El objetivo no es eliminar la ansiedad, sino aprender a reconocer cuándo está siendo útil y cuándo necesita ser regulada."]];
const items5Act: Pair[] = [["ACT proposes that suffering increases when we continually fight thoughts, emotions, or situations we cannot control.", "ACT propone que el sufrimiento aumenta cuando luchamos constantemente contra pensamientos, emociones o situaciones que no podemos controlar."], ["Rather than eliminating difficult emotions, we accept them as human and direct action toward what we value.", "En lugar de intentar eliminar emociones difíciles, aprendemos a aceptarlas como parte de la experiencia humana y dirigir nuestras acciones hacia aquello que realmente valoramos."], ["Presence lets us respond flexibly instead of reacting automatically.", "Estar presentes nos permite responder con mayor flexibilidad en lugar de reaccionar automáticamente."], ["The question shifts from “How do I stop feeling anxiety?” to “What action can I choose today, according to my values, even while anxiety is present?”", "La pregunta deja de ser “¿Cómo hago para dejar de sentir ansiedad?” y pasa a ser “¿Qué acción puedo elegir hoy, de acuerdo con mis valores, aun cuando exista ansiedad?”"]];
const items5Polyvagal: Pair[] = [["Fight: trying to control, arguing, reacting impulsively, or remaining constantly alert.", "Lucha (Fight): intentar controlar, discutir, reaccionar impulsivamente o mantenerse en constante alerta."], ["Flight: avoiding situations, staying excessively busy, or escaping physically or emotionally.", "Huida (Flight): evitar situaciones, mantenerse excesivamente ocupado o escapar física o emocionalmente."], ["Freeze: feeling paralyzed, disconnected, confused, or unable to act.", "Congelamiento (Freeze): sentirse paralizado, desconectado, confundido o incapaz de actuar."], ["Fawn: continually prioritizing others’ needs to feel safe, avoid conflict, or seek approval.", "Complacencia (Fawn): priorizar constantemente las necesidades de los demás para sentirse seguro, evitar conflictos o buscar aprobación."]];
const items5Highlight: Pair[] = [["These are normal survival mechanisms, not weakness or personal defects.", "Estas respuestas son mecanismos normales de supervivencia. No representan debilidad ni defectos personales."], ["After trauma, moving among several of these responses is common.", "Después de una experiencia traumática es común oscilar entre varias de estas respuestas."], ["Breathing, grounding, and mindfulness help the nervous system return to safety, connection, and regulation.", "Las prácticas de respiración, grounding y atención plena ayudan al sistema nervioso a regresar a un estado de mayor seguridad, conexión y regulación."]];
const items5Intervention: Pair[] = [["Return to the present through the five senses.", "Regresar al momento presente utilizando los cinco sentidos."], ["Practice grounding focused on the here and now.", "Practicar ejercicios de grounding centrados en el “aquí y ahora”."], ["Consciously observe what can be seen, heard, touched, smelled, and felt now.", "Observar conscientemente aquello que pueden ver, escuchar, tocar, oler y sentir en este momento."], ["Practice presence by literally stopping to smell the roses, using smell and observation as anchors.", "Practicar la presencia plena mediante el ejercicio de “detenerse a oler las rosas”, utilizando literalmente el olfato y la observación consciente como un ancla al presente."], ["Identify how the body changes before and after the exercise.", "Identificar cómo cambia el cuerpo antes y después del ejercicio."], ["Practice conscious breathing while observing the environment without trying to change it.", "Practicar respiración consciente mientras observan el entorno sin intentar cambiarlo."]];
const items5Processing: Pair[] = [["Where was your mind most often: past, future, or present?", "¿Dónde notaste que estaba tu mente con mayor frecuencia: en el pasado, en el futuro o en el presente?"], ["What changed when you directed attention to the present?", "¿Qué cambió cuando dirigiste tu atención al momento presente?"], ["Which automatic response do you recognize most: fight, flight, freeze, or fawn?", "¿Qué respuesta automática reconoces con mayor frecuencia en ti: lucha, huida, congelamiento o complacencia?"], ["How does your body usually respond to anxiety?", "¿Cómo suele responder tu cuerpo cuando experimenta ansiedad?"], ["What was hardest about staying present?", "¿Qué fue lo más difícil de permanecer en el presente?"], ["What strategy would you like to practice when your mind moves ahead or returns to the past?", "¿Qué estrategia te gustaría practicar cuando notes que tu mente comienza a adelantarse al futuro o regresar constantemente al pasado?"], ["What does living one hour, day, or week at a time mean to you?", "¿Qué significa para ti vivir una hora, un día o una semana a la vez?"]];

const items6Concepts: Pair[] = [["Depressive symptoms may appear after a crisis and do not always mean a depressive disorder.", "Los síntomas depresivos pueden aparecer después de una crisis y no siempre significan un trastorno depresivo."], ["Apathy and exhaustion can be normal responses after trauma.", "La apatía y el agotamiento pueden ser respuestas normales después de una experiencia traumática."], ["Sleep, nourishment, and caring for the body are part of emotional recovery.", "Dormir, alimentarse y cuidar del cuerpo forman parte de la recuperación emocional."], ["There are adaptive and maladaptive coping strategies.", "Existen estrategias de afrontamiento adaptativas y desadaptativas."], ["The language we use with ourselves influences thoughts, emotions, and behavior.", "El lenguaje que utilizamos con nosotros mismos influye en nuestros pensamientos, emociones y comportamientos."], ["We can transform inner dialogue from “I can’t” toward “I can,” “I will,” and “I am becoming.”", "Podemos aprender a transformar el diálogo interno desde el “no puedo” hacia el “puedo”, “voy a” y “me estoy convirtiendo en”."]];
const items6Objectives: Pair[] = [["Recognize common post-crisis symptoms such as apathy, exhaustion, and low motivation.", "Reconocer síntomas comunes posteriores a una crisis, como apatía, agotamiento y desmotivación."], ["Differentiate adaptive and maladaptive coping strategies.", "Diferenciar entre estrategias de afrontamiento adaptativas y desadaptativas."], ["Understand the CBT relationship among thoughts, emotions, and behavior.", "Comprender la relación entre pensamientos, emociones y comportamientos desde la Terapia Cognitivo-Conductual (CBT)."], ["Strengthen self-esteem and self-concept through more compassionate, realistic self-talk.", "Fortalecer la autoestima y el autoconcepto mediante un diálogo interno más compasivo y realista."], ["Identify concrete self-care actions that support recovery.", "Identificar acciones concretas de autocuidado que favorezcan la recuperación."]];
const items6Explain: Pair[] = [["Physical and emotional fatigue are common after a crisis.", "Después de una crisis es común experimentar cansancio físico y emocional."], ["Some people may feel unmotivated, disconnected, or without energy for previously enjoyable activities.", "Algunas personas pueden sentirse desmotivadas, desconectadas o sin energía para realizar actividades que antes disfrutaban."], ["Apathy, exhaustion, and reduced motivation can be normal responses after intense stress.", "La apatía, el agotamiento y la disminución de la motivación pueden formar parte de una respuesta normal del organismo después de una situación altamente estresante."], ["These reactions do not mean a person is weak or that they will last forever.", "Estas reacciones no significan necesariamente que la persona sea débil ni que permanecerán para siempre."]];
const items6PhysicalCare: Pair[] = [["Get enough sleep.", "Dormir lo suficiente."], ["Eat regularly and nutritiously.", "Alimentarse de manera regular y nutritiva."], ["Stay hydrated.", "Mantenerse hidratado."], ["Move the body according to each person’s abilities.", "Mover el cuerpo de acuerdo con las posibilidades de cada persona."], ["Seek moments of rest and recovery.", "Buscar momentos de descanso y recuperación."], ["Caring for the body is also caring for emotional health.", "Cuidar del cuerpo también es una forma de cuidar la salud emocional."]];
const items6Cbt: Pair[] = [["How we interpret a situation influences how we feel and act.", "La manera en que interpretamos una situación influye en cómo nos sentimos y en cómo actuamos."], ["After tragedy, thoughts such as “I am not enough,” “I will never get through this,” “I did not do enough,” or “I am a failure” may appear and increase hopelessness, guilt, or low motivation.", "Después de una tragedia pueden aparecer pensamientos como: “No soy suficiente”, “Nunca voy a salir de esto”, “No hice lo suficiente” o “Soy un fracaso”. Estos pensamientos pueden aumentar sentimientos de desesperanza, culpa o desmotivación."], ["We cannot always control the first thought, but we can question it and respond more realistically and compassionately.", "No siempre podemos controlar el primer pensamiento que aparece, pero sí podemos aprender a cuestionarlo y responder desde una perspectiva más realista y compasiva."], ["Instead of “I can’t,” practice “I can take one step at a time.”", "En lugar de “No puedo”, podemos practicar: “Puedo dar un paso a la vez”."], ["Practice: “I have survived difficult moments,” “I am learning to adapt,” “I am still here,” “I am building my recovery,” and “I am becoming more resilient.”", "Podemos decir: “He sobrevivido momentos difíciles antes”, “Estoy aprendiendo a adaptarme”, “Todavía estoy aquí”, “Estoy construyendo mi recuperación” y “Me estoy convirtiendo en una persona más resiliente”."], ["The language we use with ourselves directly affects emotions, decisions, and self-esteem.", "El lenguaje que utilizamos con nosotros mismos tiene un impacto directo en nuestras emociones, nuestras decisiones y nuestra autoestima."]];
const items6Adaptive: Pair[] = [["Seek support.", "Buscar apoyo."], ["Rest.", "Descansar."], ["Conscious breathing.", "Respiración consciente."], ["Physical exercise.", "Ejercicio físico."], ["Writing.", "Escritura."], ["Connection with others.", "Conexión con otras personas."], ["Spirituality, if meaningful.", "Espiritualidad (si es significativa para la persona)."], ["Maintain healthy routines.", "Mantener rutinas saludables."], ["Allow ourselves to feel emotions.", "Permitirnos sentir las emociones."]];
const items6Maladaptive: Pair[] = [["Prolonged isolation.", "Aislamiento prolongado."], ["Constant avoidance.", "Evitación constante."], ["Excessive alcohol or other substance use.", "Consumo excesivo de alcohol u otras sustancias."], ["Sleeping all day or not resting.", "Dormir todo el día o no descansar."], ["Neglecting nutrition.", "Descuidar la alimentación."], ["Demanding that we function “as before.”", "Exigirse funcionar “como antes”."], ["Constant self-criticism. The goal is not perfection, but expanding our healthy strategies.", "Criticarse constantemente. El objetivo no es ser perfectos, sino ampliar nuestro repertorio de estrategias saludables."]];
const items6Intervention: Pair[] = [["Identify the inner critic’s language and its effect on self-esteem.", "Identificar el lenguaje del crítico interno y cómo influye en la autoestima."], ["Replace self-critical thoughts with more realistic, compassionate, strengthening messages.", "Practicar el reemplazo de pensamientos autocríticos por mensajes más realistas, compasivos y fortalecedores."], ["Identify personal strengths that helped overcome difficult moments.", "Identificar fortalezas personales que han permitido superar momentos difíciles."], ["Build evidence-based affirmations: “I can…”, “I will…”, “I have survived…”, “I am learning…”, and “I am becoming…”", "Construir afirmaciones basadas en evidencia personal utilizando frases como: “Yo puedo…”, “Yo voy a…”, “He sobrevivido…”, “Estoy aprendiendo…” y “Me estoy convirtiendo en…”"], ["Develop a personal self-care plan with small, achievable actions for the next week.", "Desarrollar un plan personal de autocuidado con pequeñas acciones alcanzables para la próxima semana."]];
const items6Processing: Pair[] = [["How does your inner critic usually speak to you?", "¿Cómo suele hablarte tu crítico interno?"], ["What effect does that language have on your mood?", "¿Qué efecto tiene ese lenguaje sobre tu estado de ánimo?"], ["What phrase could you begin saying to yourself more often?", "¿Qué frase podrías comenzar a decirte con mayor frecuencia?"], ["What strengths have you used to reach this moment?", "¿Qué fortalezas has utilizado para llegar hasta este momento?"], ["What healthy coping strategy would you like to strengthen?", "¿Qué estrategia de afrontamiento saludable te gustaría fortalecer?"], ["Is there a strategy that no longer contributes to your well-being?", "¿Hay alguna estrategia que ya no esté contribuyendo a tu bienestar?"], ["What does “I have survived” mean to you?", "¿Qué significa para ti la frase “He sobrevivido”?"], ["What does saying “I can” or “I will…” mean to you?", "¿Qué significa para ti decir “Yo puedo” o “Yo voy a…”?"]];

const items7Concepts: Pair[] = [["Rebuilding meaning.", "Reconstrucción del significado."], ["Purpose.", "Propósito."], ["Post-traumatic growth.", "Crecimiento postraumático."], ["Community.", "Comunidad."], ["Helping can also be a way to process grief.", "Ayudar también puede ser una forma de elaborar el duelo."], ["Healing can grow stronger when it happens in community.", "La sanación puede fortalecerse cuando ocurre en comunidad."]];
const items7Objectives: Pair[] = [["Integrate the experience lived during the group.", "Integrar la experiencia vivida durante el grupo."], ["Explore personal purpose after adversity.", "Explorar el propósito personal después de la adversidad."], ["Identify ways to honor those affected.", "Identificar formas de honrar a quienes fueron afectados."], ["Foster connection with community and personal values.", "Favorecer la conexión con la comunidad y los valores personales."], ["Recognize each member’s positive impact on others’ process.", "Reconocer el impacto positivo que cada integrante ha tenido en el proceso de los demás."]];
const items7Psychoeducation: Pair[] = [["Purpose does not eliminate pain; it helps us walk alongside it.", "El propósito no elimina el dolor; nos ayuda a caminar junto a él."], ["Post-traumatic growth does not mean tragedy was positive, but that people can find new ways to live afterward.", "El crecimiento postraumático no significa que la tragedia haya sido positiva, sino que las personas pueden encontrar nuevas formas de vivir después de ella."], ["Meaning is built gradually and is different for each person.", "El significado se construye gradualmente y es diferente para cada persona."], ["Living with purpose can honor our losses, values, and those who remain part of our story.", "Vivir con propósito puede convertirse en una forma de honrar nuestras pérdidas, nuestros valores y a quienes continúan formando parte de nuestra historia."], ["Recovery does not always happen alone. Sharing, listening, and feeling understood can reduce isolation and strengthen belonging.", "La recuperación no siempre ocurre en soledad. Compartir experiencias, escuchar a otros y sentirnos comprendidos puede disminuir el aislamiento y fortalecer el sentido de pertenencia."], ["Although each person arrived with their own story, everyone contributed through presence, words, listening, and willingness to accompany others.", "Aunque cada persona llegó con su propia historia, todos han contribuido al proceso del grupo mediante su presencia, sus palabras, su escucha y su disposición para acompañar a los demás."]];
const items7Intervention: Pair[] = [["Reflect on the path traveled since the first session.", "Reflexionar sobre el camino recorrido desde la primera sesión."], ["Identify the most significant personal changes.", "Identificar los cambios personales más significativos."], ["Explore the purpose participants wish to continue building after the group.", "Explorar el propósito que desean seguir construyendo después del grupo."], ["Recognize how each member contributed to the collective process.", "Reconocer cómo cada integrante contribuyó al proceso colectivo."], ["Share something learned from another group member.", "Compartir aquello que aprendieron de otro miembro del grupo."], ["Express gratitude or recognition for a meaningful moment during the sessions.", "Expresar gratitud o reconocimiento por algún momento significativo vivido durante las sesiones."], ["Reflect on how healing can also happen in community.", "Reflexionar sobre cómo el proceso de sanar también puede ocurrir en comunidad."]];
const items7Invitation: Pair[] = [["Something learned from another member.", "Algo que aprendió de otro integrante del grupo."], ["A meaningful moment during the sessions.", "Un momento que haya sido significativo durante las sesiones."], ["A quality observed in another participant.", "Una cualidad que haya observado en otro participante."], ["How it felt to accompany and be accompanied during this process.", "Cómo se sintió al acompañar y ser acompañado durante este proceso."]];
const items7Processing: Pair[] = [["What changed in you since the first session?", "¿Qué cambió en ti desde la primera sesión?"], ["What have you discovered about who you are today?", "¿Qué has descubierto sobre quién eres hoy?"], ["What meaning does this experience have for you now?", "¿Qué significado tiene ahora esta experiencia para ti?"], ["What would you like to keep from this group?", "¿Qué te llevas de este grupo que quisieras conservar?"], ["What did you learn from another member?", "¿Qué aprendiste de alguno de los integrantes?"], ["Was there a shared moment that was especially meaningful?", "¿Hubo algún momento compartido que haya sido especialmente significativo para ti?"], ["What was it like to allow yourself to heal alongside others?", "¿Cómo fue para ti permitirte sanar junto a otras personas?"], ["What purpose do you wish to continue building from today?", "¿Qué propósito deseas seguir construyendo a partir de hoy?"]];
const items7Feedback: Pair[] = [["Today I take with me…", "Hoy me llevo…"], ["What I learned most from this group was…", "Lo que más aprendí de este grupo fue…"], ["A quality I recognize in myself today is…", "Una cualidad que reconozco en mí hoy es…"], ["A quality I admire in another member is…", "Una cualidad que admiro de otro integrante es…"], ["Share feedback about the group experience.", "Compartir retroalimentación sobre la experiencia del grupo."], ["Reflect on resources and learning to continue using in daily life.", "Reflexionar sobre los recursos y aprendizajes que desean continuar utilizando en su vida cotidiana."], ["Exchange contact information only if both parties wish, respecting each person’s privacy and decision.", "Intercambiar información de contacto (por ejemplo, números telefónicos) únicamente si ambas partes así lo desean, respetando la decisión y privacidad de cada participante."], ["Say goodbye while recognizing the path traveled and the value of sharing this process.", "Despedirse del grupo reconociendo el camino recorrido y el valor de haber compartido este proceso juntos."]];

async function run(): Promise<void> {
  const uri = process.env.MONGO_URI;
  if (!uri) throw new Error("MONGO_URI is required.");
  await mongoose.connect(uri);
  const curriculum = await Curriculums.findOne({ slug: "when-the-earth-changes" }).select("_id slug");
  if (!curriculum) throw new Error("The 'When the Earth Changes' curriculum was not found.");

  for (const data of [buildSession5(), buildSession6(), buildSession7()]) {
    await Sessions.findOneAndUpdate(
      { curriculumId: curriculum._id, number: data.number },
      { $set: { ...data, curriculumId: curriculum._id } },
      { upsert: true, runValidators: true, setDefaultsOnInsert: true },
    );
  }
  console.log(`Sessions 5–7 added to ${curriculum.slug}.`);
  await mongoose.disconnect();
}

run().catch(async (error) => {
  console.error(error instanceof Error ? error.message : error);
  await mongoose.disconnect();
  process.exitCode = 1;
});
